name: simple_calculator
description: "A simple calculator app that keeps track of the calculations on a scrollable notebook at the bottom."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  # decimal module used to avoid floating point errors in the calculations
  decimal: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/table-top.jpeg